---
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: mutant_detector_development

test:
  <<: *default
  database: 'mutant_detector_test'

production:
  <<: *default
